apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: nginx-deployment-aws-secrets
  namespace: production
spec:
  provider: aws
  secretObjects:
    - secretName: nginxsecrets
      type: Opaque
      data:
        - objectName: secret_token
          key: NGINX_API_TOKEN
  parameters:
    objects: |
      - objectName: "prod/nginx-svc/token"
        objectType: "secretsmanager"
        # jmesPath:
        #   - path: "NGINX_API_TOKEN"
        objectAlias: "secret_token"